### ISSUE TITLE
CMake restructuring

### ISSUE THREAD

**Issue by DinkoAtanasov** [leenderthayen/CRADLE#1]
Hi, 

I would suggest to require the USER to set an environmental variable such as "BSGPATH" for the BSG working directory, or even automatically to add it during compilation (don't know which one would be simpler).
`set(BSG_INSTALL_DIR "~/BSG")`
change to 
`set(BSG_INSTALL_DIR $ENV{BSGPATH})`

 Furthermore, the file structure in BSG should correspond to the CRADLE's cmake folder expectations. Currently, the folder structure from  
CRADLE repo:
`set(BSG_LIBRARIES "${BSG_INSTALL_DIR}/lib/nme/libnme.so;${BSG_INSTALL_DIR}/lib/bsg/libbsg.so")`
which is not the case for the BSG one as the compiled libraries are put directly in "./build/lib/". 
I think the folder structure in BSG is the one to follow :) then just change to: 

`set(BSG_LIBRARIES "${BSG_INSTALL_DIR}/build/lib/libnme.so;${BSG_INSTALL_DIR}/build/lib/libbsg.so")`

Dinko

**Comment by leenderthayen** [comment]
Hi Dinko,

That's a good comment. Regarding the first: The idea is to eventually make the system find BSG itself, so these things need not be specified manually. This is implemented, but not tested as I didn't have the time for it.

Regarding the build srtructure:
The way is it written right now for the libraries is based on the install structures, i.e. when you perform make install (you can specify the install location using the -DCMAKE_INSTALL_PREFIX option when running cmake). I'll put it on the list to make sure it's the same structure.

I'm travelling again this week, so expect some delays for such things.

**Comment by DinkoAtanasov** [comment]
> Hi Dinko,
> 
> That's a good comment. Regarding the first: The idea is to eventually make the system find BSG itself, so these things need not be specified manually. This is implemented, but not tested as I didn't have the time for it.
> 
> Regarding the build srtructure:
> The way is it written right now for the libraries is based on the install structures, i.e. when you perform make install (you can specify the install location using the -DCMAKE_INSTALL_PREFIX option when running cmake). I'll put it on the list to make sure it's the same structure.
> 
> I'm travelling again this week, so expect some delays for such things.

Oh yes, you are right, I forgot to "make install" at the end. Regarding the first suggestion - Great idea :) 
I have a working version now which I can play with. Will keep you posted if there are some problems in my tests.
